/* =============================================================================
   CHRONO-WEB — DATA FILE
   =============================================================================
   The editable brain of the visualization. The viewer (chronoweb.html) reads
   window.CHRONOWEB_DATA below. To grow the web after verifying a new thread,
   append to `threads`, `nodes`, `edges`, and (if new) `entities`.

   STRUCTURE
   ---------
   - COMPLEX: a top-level "structure" Dixon names. MIC / FIC / TIC (+ PL parking lot).
   - THREAD : one sub-claim within a complex, carrying its own verdict.
   - NODE   : an atomic claim with a verification STATE.
   - EDGE   : an inferential move ("therefore...") with a GRADE. The lie usually
              lives in the edge, not the node.
   - ENTITY : a recurring player / event / document (the Fed, BlackRock, NSAM 263,
              the Magnificent Seven, Aladdin). Entities are the WEB JUNCTIONS — when
              a new thread's node touches an existing entity, you don't re-research
              it; the new node welds onto the existing hub. A hub touched by more
              than one COMPLEX is a major crossover.

   FIELD REFERENCE
   ---------------
   complex: { id, label, color }                       id ∈ MIC | FIC | TIC | PL
   thread:  { id, complex, title, claim, speaker, source, verdict, color }
            verdict ∈ FAILS | PARTIALLY_HOLDS | LARGELY_HOLDS | MIXED | OPEN
   node:    { id, thread, label, claim, layer, date, concreteness, sourcing,
              state, note, primarySource, entities:[entityId,...] }
            layer ∈ fact | interp | framing | anchor | parked
            state ∈ Verified | Partially Verified | Falsified | Misattributed
                  | Source Not Found | Source Says Otherwise | Unverifiable | Open
   edge:    { id, thread, from, to, type, grade, note }
            type  ∈ causal_inference | predictive | incentive | depends_on
                  | cites_as_evidence | same_entity | temporal
            grade ∈ Warranted | Weak | Unwarranted | NonSequitur
   entity:  { id, label, kind, date, note }
            kind  ∈ structure | org | person | event | document | speaker | concept
   ============================================================================= */

window.CHRONOWEB_DATA = {

  meta: {
    title: "Chrono-Web",
    subtitle: "A growing map of verified claims and the inferences that connect them",
    sourceContext:
      "Multiple sources mapped into one web. Subject-matter complexes: MIC (military-industrial), " +
      "FIC (financial-industrial), TIC (technological-industrial). Each claim is decomposed into " +
      "nodes (facts/interpretations) and edges (inferences). When a NEW source lands on an existing " +
      "node it corroborates, clarifies, contests, or disproves it (see web_integration_protocol.md). " +
      "Cross-source links show where sources converge or collide; the RX complex collects open conflicts."
  },

  /* ---------------------------------------------------------------- SOURCES */
  /* Provenance registry. Every thread carries a `source`. */
  sources: [
    { id:"src_dixon",   label:"Simon Dixon — Impact Theory", speaker:"Simon Dixon",
      show:"Impact Theory", url:"https://www.youtube.com/watch?v=u4RawKdA_gM" },
    { id:"src_griffin", label:"G. Edward Griffin — 'The Creature from Jekyll Island' (WiM401)",
      speaker:"G. Edward Griffin / Robert Breedlove", show:"What is Money?",
      url:"https://www.youtube.com/watch?v=WTIP3IhG3Xo" },
    { id:"src_webb", label:"Whitney Webb — 'Epstein, Intelligence & the Global Network of Power'",
      speaker:"Whitney Webb / Peter McCormack", show:"The Peter McCormack Show",
      url:"https://www.youtube.com/watch?v=EwejUh3m9Fg" }
  ],

  /* -------------------------------------------------------------- COMPLEXES */
  complexes: [
    { id: "MIC", label: "Military-Industrial",      color: "#cf7d3a" },
    { id: "FIC", label: "Financial-Industrial",     color: "#2b9fb3" },
    { id: "TIC", label: "Technological-Industrial", color: "#9b6cd6" },
    { id: "IIC", label: "Intelligence-Industrial",  color: "#5661c4" },
    { id: "RX",  label: "Open Reconciliations",     color: "#d2509f" },
    { id: "PL",  label: "Parking Lot",              color: "#6b7686" }
  ],

  /* ---------------------------------------------------------------- THREADS */
  threads: [
    /* ===== MIC ===== */
    { id:"T1", complex:"MIC", title:"JFK challenged the structure → was dealt with",
      claim:"\"JFK is one of the most obvious examples\" of someone who challenged the structure and was dealt with.",
      speaker:"Simon Dixon", source:"Impact Theory, ~min 9", verdict:"FAILS", color:"#cf7d3a" },
    { id:"T2", complex:"MIC", title:"Earnings predict the next war zone",
      claim:"Reading defense-prime balance sheets and where the contracts are tells you where the next war zone will be, because they prepare.",
      speaker:"Simon Dixon", source:"Impact Theory, ~min 2", verdict:"PARTIALLY_HOLDS", color:"#cf7d3a" },
    { id:"T3", complex:"MIC", title:"MIC roster + 'war > defense contracts'",
      claim:"The MIC (Lockheed, General Dynamics, Raytheon, Boeing, BAE) is a machine that requires continual revenue — more profitable is war, less profitable is defense contracts.",
      speaker:"Simon Dixon", source:"Impact Theory, ~min 1", verdict:"LARGELY_HOLDS", color:"#cf7d3a" },

    /* ===== FIC ===== */
    { id:"FIC1", complex:"FIC", title:"Money is created as credit by private banks",
      claim:"\"Money is created by a private commercial bank… a loan has to exist for a bank to create credit… it's just a digital entry.\"",
      speaker:"Simon Dixon", source:"Impact Theory (u4RawKdA_gM)", verdict:"LARGELY_HOLDS", color:"#2b9fb3" },
    { id:"FIC2", complex:"FIC", title:"Central banking is a structural Ponzi",
      claim:"\"There's not enough money to pay the interest… the system must grow at all times or it breaks.\"",
      speaker:"Simon Dixon", source:"Impact Theory", verdict:"FAILS", color:"#2b9fb3" },
    { id:"FIC3", complex:"FIC", title:"Three central banks in America",
      claim:"First Bank, Second Bank, and the Federal Reserve — three central banks across US history.",
      speaker:"Simon Dixon", source:"Impact Theory", verdict:"LARGELY_HOLDS", color:"#2b9fb3" },
    { id:"FIC4", complex:"FIC", title:"Engineered: Dutch → British → America → global",
      claim:"Central banking was engineered first in the Dutch Empire, then British, then three times in America, then made global.",
      speaker:"Simon Dixon", source:"Impact Theory", verdict:"PARTIALLY_HOLDS", color:"#2b9fb3" },
    { id:"FIC5", complex:"FIC", title:"BlackRock cluster (Aladdin / Fink / Masters / Aramco)",
      claim:"BlackRock is \"the most important node in the West\"; Aladdin controls ~$25T; Fink invented the MBS; Masters invented the CDS; Aramco's CEO got a board seat.",
      speaker:"Simon Dixon", source:"Impact Theory", verdict:"MIXED", color:"#2b9fb3" },
    { id:"FIC6", complex:"FIC", title:"Everything is subordinate to finance (the hierarchy)",
      claim:"Every complex needs capital, so the FIC sits above all of them.",
      speaker:"Simon Dixon", source:"Impact Theory", verdict:"PARTIALLY_HOLDS", color:"#2b9fb3" },
    { id:"FIC7", complex:"FIC", title:"Government is a piggy bank for bondholders",
      claim:"\"Government is just another bondholder's piggy bank; politicians are actors.\"",
      speaker:"Simon Dixon", source:"Impact Theory", verdict:"PARTIALLY_HOLDS", color:"#2b9fb3" },
    { id:"FIC8", complex:"FIC", title:"Control levers: lobbying, blackmail, capital access",
      claim:"The FIC controls via lobbying, deep-state black operations for blackmail, and capital-market access.",
      speaker:"Simon Dixon", source:"Impact Theory", verdict:"PARTIALLY_HOLDS", color:"#2b9fb3" },

    /* ===== TIC ===== */
    { id:"TIC1", complex:"TIC", title:"Almost 50% of the S&P 500 is the Magnificent Seven",
      claim:"\"Almost 50% of the S&P 500 is the Magnificent Seven.\"",
      speaker:"Simon Dixon", source:"Impact Theory (u4RawKdA_gM)", verdict:"PARTIALLY_HOLDS", color:"#9b6cd6" },
    { id:"TIC2", complex:"TIC", title:"Engineer perception via 'neo media' & algorithms",
      claim:"The complex engineers perception through 'neo media' and performs operations by controlling algorithms.",
      speaker:"Simon Dixon", source:"Impact Theory", verdict:"PARTIALLY_HOLDS", color:"#9b6cd6" },
    { id:"TIC3", complex:"TIC", title:"Tech is subordinate to finance (needs capital)",
      claim:"These tech companies are subordinate to finance because they need access to capital.",
      speaker:"Simon Dixon", source:"Impact Theory", verdict:"FAILS", color:"#9b6cd6" },
    { id:"TIC4", complex:"TIC", title:"Components: data centers, algorithms, the Mag 7",
      claim:"The TIC is made of data centers, algorithms, and the Magnificent Seven.",
      speaker:"Simon Dixon", source:"Impact Theory", verdict:"LARGELY_HOLDS", color:"#9b6cd6" },

    /* ===== FIC — second source: G. Edward Griffin (WiM401) ===== */
    { id:"GA", complex:"FIC", srcId:"src_griffin", title:"The Fed is a private cartel, not a government agency",
      claim:"\"It is not, repeat, not an agency of the federal government… a cartel of private banks,\" conceived in secret on Jekyll Island (1910), passed 1913.",
      speaker:"G. Edward Griffin", source:"What is Money? WiM401, Thread A", verdict:"PARTIALLY_HOLDS", color:"#2b9fb3" },
    { id:"GB", complex:"FIC", srcId:"src_griffin", title:"The Fed encourages war",
      claim:"Inflation hides war costs that explicit taxation would block — so you get more war (war on terror ~$2.5T, ~$80k/household).",
      speaker:"G. Edward Griffin / Breedlove", source:"What is Money? WiM401, Thread B", verdict:"PARTIALLY_HOLDS", color:"#2b9fb3" },
    { id:"GC", complex:"FIC", srcId:"src_griffin", title:"Inflation is a hidden tax (the 1913→1990 gold-wage proof)",
      claim:"Measured in gold, wages rose only 73% (≈1%/yr) vs a 3,233% nominal raise — so the big paycheck was 'meaningless.'",
      speaker:"G. Edward Griffin / Breedlove", source:"What is Money? WiM401, Thread C", verdict:"PARTIALLY_HOLDS", color:"#2b9fb3" },
    { id:"GP", complex:"PL", srcId:"src_griffin", title:"Griffin parking lot (WiM401)",
      claim:"Parked tangents from the Griffin interview — quick states only.",
      speaker:"G. Edward Griffin / Breedlove", source:"What is Money? WiM401", verdict:"OPEN", color:"#6b7686" },

    /* ===== IIC — third source: Whitney Webb (Epstein / intelligence) ===== */
    { id:"WA", complex:"IIC", srcId:"src_webb", title:"A meta-cartel runs the world (born from Operation Underworld)",
      claim:"The mob+US-intelligence fusion of WWII 'provably continued,' so intelligence agencies became the runners of organized-crime rackets — a meta-cartel.",
      speaker:"Whitney Webb", source:"McCormack Show, Thread A", verdict:"PARTIALLY_HOLDS", color:"#5661c4" },
    { id:"WB", complex:"IIC", srcId:"src_webb", title:"The sweetheart deal proves Epstein was a protected intelligence asset",
      claim:"Epstein's 2008 non-prosecution deal + co-conspirator immunity proves state/intelligence protection.",
      speaker:"Whitney Webb", source:"McCormack Show, Thread B", verdict:"PARTIALLY_HOLDS", color:"#5661c4" },
    { id:"WC", complex:"IIC", srcId:"src_webb", title:"Maxwell recruited Epstein into Mossad",
      claim:"Robert Maxwell (a Mossad conduit) recruited Epstein into Israeli intelligence — per Ari Ben-Menashe, corroborated by Hersh/Gordon Thomas.",
      speaker:"Whitney Webb", source:"McCormack Show, Thread C", verdict:"FAILS", color:"#5661c4" },
    { id:"WD", complex:"IIC", srcId:"src_webb", title:"17 White House visits + Middleton's death = a cover-up",
      claim:"Epstein's 17 Clinton-WH visits via Mark Middleton, plus Middleton's bizarre 2022 death, = a cover-up ('China Gate').",
      speaker:"Whitney Webb", source:"McCormack Show, Thread D", verdict:"PARTIALLY_HOLDS", color:"#5661c4" },
    { id:"WE", complex:"IIC", srcId:"src_webb", title:"The Senate BCCI report says the bank trafficked minors to elites",
      claim:"The 1992 Senate (Kerry–Brown) BCCI report documents the bank trafficking minors to its elite members.",
      speaker:"Whitney Webb", source:"McCormack Show, Thread E", verdict:"LARGELY_HOLDS", color:"#5661c4" },
    { id:"WP", complex:"IIC", srcId:"src_webb", title:"Webb parking lot",
      claim:"Parked tangents from the Webb interview — quick states, weld points into the rest of the web.",
      speaker:"Whitney Webb", source:"McCormack Show", verdict:"OPEN", color:"#5661c4" },

    /* ===== Open Reconciliations — cross-source conflicts awaiting research ===== */
    { id:"RX1", complex:"RX", srcId:"src_dixon", title:"Open reconciliations",
      claim:"Propositions where two sources genuinely disagree and neither is decisively right — the research queue, made visible.",
      speaker:"(synthesis)", source:"web_integration_protocol.md §3", verdict:"OPEN", color:"#d2509f" },

    /* ===== Parking Lot ===== */
    { id:"PL", complex:"PL", srcId:"src_dixon", title:"Parking Lot (not yet researched)",
      claim:"Tangents parked during the active dives — the growth frontier of the web.",
      speaker:"Simon Dixon", source:"Impact Theory", verdict:"OPEN", color:"#6b7686" }
  ],

  /* --------------------------------------------------------------- ENTITIES */
  entities: [
    { id:"dixon",        label:"Simon Dixon",                  kind:"speaker",   note:"Origin of every claim — the common root of the web." },
    { id:"fed",          label:"Federal Reserve",              kind:"org",       note:"FIC target in MIC-T1; 'three central banks' (FIC-3) & 'Ponzi' (FIC-2) weld here too." },
    { id:"fic",          label:"Financial-Industrial Complex", kind:"structure", note:"Dixon's apex structure. Entity verdict: PARTIALLY HOLDS — real plumbing, inflated control." },
    { id:"mic",          label:"Military-Industrial Complex",  kind:"structure", note:"Spans T1 (Vietnam/détente), T2 (earnings), T3 (roster), and FIC-6 (needs capital)." },
    { id:"tic",          label:"Technological-Industrial Complex", kind:"structure", note:"Entity verdict: PARTIALLY HOLDS — real substrate, inflated magnitude, mis-assigned agency." },
    { id:"cia",          label:"CIA / Allen Dulles",           kind:"org",       note:"Dulles fired Nov 1961 post–Bay of Pigs; 'splinter' quote unsourced." },
    { id:"mafia",        label:"Mafia / organized crime",      kind:"structure", note:"Strongest surviving JFK motive — but outside Dixon's complexes." },
    { id:"assassination",label:"JFK assassination",            kind:"event",     date:"1963-11-22", note:"Dallas, Nov 22 1963. Anchor event of T1." },
    { id:"eo11110",      label:"EO 11110 (silver certs)",      kind:"document",  date:"1963-06-04", note:"Expanded Fed notes — opposite of the anti-Fed myth." },
    { id:"nsam263",      label:"NSAM 263 (Vietnam)",           kind:"document",  date:"1963-10-11", note:"Withdrawal of 1,000 by end-1963." },
    { id:"warren",       label:"Warren Commission",            kind:"document",  date:"1964",       note:"1964: lone gunman, Oswald." },
    { id:"hsca",         label:"HSCA",                         kind:"document",  date:"1979",       note:"1979: 'probably a conspiracy' — on since-discredited acoustics." },
    { id:"primes",       label:"Defense primes (sector)",      kind:"org",       note:"Welds T2 (file earnings), T3 (roster), and FIC-6 (need capital)." },
    { id:"lockheed",     label:"Lockheed Martin",              kind:"org",       note:"#1 defense contractor, $64.6B defense revenue 2024." },
    { id:"rtx",          label:"RTX (Raytheon)",               kind:"org",       note:"Raytheon + United Technologies merged 2020 → RTX." },
    { id:"gd",           label:"General Dynamics",             kind:"org",       note:"$93.6B backlog." },
    { id:"boeing",       label:"Boeing (Defense)",             kind:"org",       note:"Major via Boeing Defense, Space & Security." },
    { id:"bae",          label:"BAE Systems",                  kind:"org",       note:"UK's largest defense firm; LSE-listed." },
    { id:"secfilings",   label:"SEC filings (10-K/10-Q)",      kind:"document",  note:"Public segment results — raw material of T2, T3, FIC-8." },
    { id:"blackrock",    label:"BlackRock",                    kind:"org",       note:"Graduated from Parking Lot → fully researched in FIC-5. Real centrality; 'controls $25T' is monitor-vs-control inflation." },
    { id:"aladdin",      label:"Aladdin (platform)",           kind:"org",       note:"Monitors/risk-manages ~$21–25T for 200+ external clients — does NOT control/allocate it." },
    { id:"fink",         label:"Larry Fink",                   kind:"person",    note:"Pioneered the CMO at First Boston (~1983) — did NOT invent the MBS (predates him; Ginnie Mae 1970)." },
    { id:"bmasters",     label:"Blythe Masters (CDS)",         kind:"person",    note:"Led the JPMorgan team that built the credit default swap, mid-1990s (Verified)." },
    { id:"aramco",       label:"Saudi Aramco",                 kind:"org",       note:"CEO Amin Nasser joined BlackRock board as independent director, July 2023 (Verified)." },
    { id:"boe",          label:"Bank of England",              kind:"org",       date:"1694", note:"Source for money-creation (2014 paper) and the 1694 central-bank template (FIC-1, FIC-4)." },
    { id:"mag7",         label:"Magnificent Seven",            kind:"org",       note:"Apple, Microsoft, Alphabet, Amazon, Nvidia, Meta, Tesla. ~34–35% of S&P — not 'almost 50%'." },
    { id:"algos",        label:"Recommendation algorithms",    kind:"concept",   note:"'Neo media'. Shape attention (Verified); used for state-linked influence ops (Verified)." },
    { id:"govbond",      label:"Government / bond markets",    kind:"structure", note:"Governments finance via bonds and are constrained by them (Verified); 'piggy bank' is framing." },
    { id:"aicapex",      label:"AI-capex debt binge 2025–26",  kind:"event",     note:"Oracle, Meta, Amazon, Alphabet debt issuance (~$108B hyperscaler debt 2025). The one timely kernel under TIC-3 / FIC-6." },
    /* --- added with the Griffin (WiM401) source --- */
    { id:"griffin",      label:"G. Edward Griffin",            kind:"speaker",   note:"Second source. Author of 'The Creature from Jekyll Island' (via Breedlove, WiM401)." },
    { id:"jekyll",       label:"Jekyll Island meeting (1910)", kind:"event",     date:"1910-11", note:"Secret meeting that drafted the Aldrich Plan → Federal Reserve Act 1913. Verified even by the Fed's own history. The concrete US 'engineering' event Dixon's FIC-4 only gestured at." },
    { id:"treasury",     label:"US Treasury",                  kind:"org",       note:"The Fed remits ~all net earnings here (~$97.7B in 2015, ~$86.9B in 2020) — the fact that most cleanly complicates 'private cartel' and the FIC-apex framing." },
    { id:"waronterror",  label:"War on Terror",                kind:"event",     note:"Griffin/Breedlove's case for inflation-financed war. Best independent estimate ~$8T (Brown Costs of War), not the $2.5T cited." },
    { id:"gold",         label:"Gold / the gold yardstick",   kind:"concept",   note:"Griffin measures wages in gold to expose inflation. But gold was price-fixed then spiked 1971–80 — a volatile ruler; the 73% figure is an artifact of the 1990 endpoint." },
    /* --- added with the Webb / Epstein (IIC) source --- */
    { id:"webb",         label:"Whitney Webb",                kind:"speaker",   note:"Third source. Investigative journalist; 'meta-cartel' thesis. High factual hit-rate; the overreach is the aggregation edge, not the facts." },
    { id:"epstein",      label:"Jeffrey Epstein",             kind:"person",    note:"Central hub of the intelligence-network thesis. Anomalous 2008 deal is verified; 'intelligence asset' is the contested interpretation." },
    { id:"opunderworld", label:"Operation Underworld (WWII)", kind:"event",     date:"1942", note:"US Office of Naval Intelligence + Luciano/Lansky mob, 1942–45. Verified, once-suppressed (Herlands Report). The founding fact of Webb's thesis." },
    { id:"cia_mafia",    label:"Intel–crime collaboration",   kind:"concept",   note:"The recurring pattern: CIA–Mafia Castro plots, Contra-cocaine, MKUltra. Episodic and real — but 'one permanent structure' is the overreach." },
    { id:"maxwell",      label:"Robert Maxwell",              kind:"person",    note:"Israeli-intel ties are documented; 'recruited Epstein for Mossad' rests on unreliable sourcing." },
    { id:"benmenashe",   label:"Ari Ben-Menashe",             kind:"person",    note:"Load-bearing source for the Maxwell-recruited-Epstein claim — repeatedly assessed as an unreliable fabulist. The weakest pillar under the heaviest load." },
    { id:"mossad",       label:"Mossad / Israeli intel",      kind:"org",       note:"Maxwell's ties are real; the Epstein-recruitment link is unproven as sourced." },
    { id:"bcci",         label:"BCCI (bank)",                 kind:"org",       note:"1992 Kerry–Brown Senate report documents institutional procurement of teenage girls for elite clients. Webb's most solid citation." },
    { id:"middleton",    label:"Mark Middleton",              kind:"person",    note:"Facilitated Epstein's White House access; grotesque 2022 death ruled suicide, records sealed at family request." },
    { id:"clinton",      label:"Clinton White House",         kind:"person",    note:"Epstein logged ~17 visits 1993–95, many via Middleton. Verified." },
    { id:"palantir",     label:"Palantir / In-Q-Tel",         kind:"org",       note:"DARPA 'Total Information Awareness' → privatized surveillance; In-Q-Tel (CIA) early investor. Welds the intel domain to TIC." }
  ],

  /* ------------------------------------------------------------------ NODES */
  nodes: [

    /* ============================== MIC — T1 (JFK) ====================== */
    { id:"n_2a", thread:"T1", label:"JFK was assassinated", layer:"anchor",
      claim:"Base fact: shot dead, Dallas, Nov 22 1963.",
      date:"1963-11-22", concreteness:"High", sourcing:"Public",
      state:"Verified", note:"Anchor node — confirmed first.",
      primarySource:"Historical record", entities:["assassination"] },
    { id:"n_1a_fact", thread:"T1", label:"Signed EO 11110", layer:"fact",
      claim:"JFK signed Executive Order 11110 re: silver certificates.",
      date:"1963-06-04", concreteness:"High", sourcing:"Implied (public doc)",
      state:"Verified", note:"Jun 4 1963.",
      primarySource:"American Presidency Project / Federal Register", entities:["eo11110"] },
    { id:"n_1c_fire", thread:"T1", label:"Fired Allen Dulles", layer:"fact",
      claim:"JFK fired / forced out CIA Director Allen Dulles.",
      date:"1961-11", concreteness:"High", sourcing:"Public",
      state:"Verified", note:"Dulles out Nov 1961 post–Bay of Pigs; Bissell too.",
      primarySource:"Historical record", entities:["cia"] },
    { id:"n_1c_quote", thread:"T1", label:"\"Splinter CIA into a thousand pieces\"", layer:"fact",
      claim:"JFK said he would splinter the CIA into a thousand pieces.",
      date:"1966-04-25", concreteness:"Medium", sourcing:"Press-attributed",
      state:"Source Not Found", note:"Sole attribution = anonymous source, NYT, Apr 25 1966 (3 yrs posthumous); phrase predates JFK. Provenance fails.",
      primarySource:"NYT 1966 (anonymous) — unverifiable provenance", entities:["cia"] },
    { id:"n_1d_fact", thread:"T1", label:"Ordered Vietnam drawdown (NSAM 263)", layer:"fact",
      claim:"JFK ordered a troop drawdown via NSAM 263.",
      date:"1963-10-11", concreteness:"High", sourcing:"Public doc",
      state:"Verified", note:"Approved Oct 11 1963; endorsed withdrawal of 1,000 by end-1963.",
      primarySource:"NSAM 263 text", entities:["nsam263","mic"] },
    { id:"n_1e_fact", thread:"T1", label:"Peace speech / test ban / steel", layer:"fact",
      claim:"American University 'peace speech', Partial Test Ban Treaty, 1962 steel-price confrontation.",
      date:"1963-06-10", concreteness:"High", sourcing:"Public",
      state:"Verified", note:"AU speech Jun 10 1963; PTBT signed Aug 5 1963; steel confrontation Apr 1962.",
      primarySource:"Public record", entities:["mic","fic"] },
    { id:"n_1f_fact", thread:"T1", label:"RFK organized-crime crackdown", layer:"fact",
      claim:"RFK ran an aggressive organized-crime crackdown.",
      date:"1961", concreteness:"High", sourcing:"Public",
      state:"Verified", note:"Prosecutions +300%, 'Get Hoffa Squad,' Marcello deported Apr 1961.",
      primarySource:"DOJ record", entities:["mafia"] },
    { id:"n_1a_interp", thread:"T1", label:"EO 11110 threatened the Fed", layer:"interp",
      claim:"EO 11110 was a move against the Federal Reserve.",
      date:"1963-06-04", concreteness:"High", sourcing:"Implied",
      state:"Falsified", note:"Did the opposite — expanded Fed Note circulation, phased out silver certs. CRS debunked the myth.",
      primarySource:"Congressional Research Service", entities:["fed","fic","eo11110"] },
    { id:"n_1b", thread:"T1", label:"Wanted to abolish the Fed", layer:"interp",
      claim:"JFK intended to abolish / challenge the Federal Reserve.",
      date:"1963", concreteness:"Low", sourcing:"None",
      state:"Falsified", note:"No evidence; reappointed Fed chair Martin and praised the Fed in 1962.",
      primarySource:"Public record", entities:["fed","fic"] },
    { id:"n_1c_interp", thread:"T1", label:"Moved to dismantle the CIA", layer:"interp",
      claim:"JFK genuinely moved to dismantle the CIA.",
      date:"1961-11", concreteness:"Medium", sourcing:"Press-attributed",
      state:"Partially Verified", note:"Real firings + anger; 'dismantle' rests on the apocryphal quote. Real friction, overstated scope.",
      primarySource:"Mixed", entities:["cia"] },
    { id:"n_1d_interp", thread:"T1", label:"NSAM 263 = real intent to exit Vietnam", layer:"interp",
      claim:"NSAM 263 reflected a real decision to exit Vietnam (a threat to the MIC).",
      date:"1963-10-11", concreteness:"High", sourcing:"Public doc",
      state:"Partially Verified", note:"Disputed. Historians split — withdrawal-proponents vs Logevall (leverage on Diem, not a withdrawal decision).",
      primarySource:"NSAM 263 + historiography", entities:["nsam263","mic"] },
    { id:"n_1e_interp", thread:"T1", label:"Détente threatened the MIC/FIC", layer:"interp",
      claim:"JFK's détente moves threatened the military/financial structure.",
      date:"1963", concreteness:"Medium", sourcing:"Public",
      state:"Partially Verified", note:"Real policy; the 'threat to the structure' link is speculative.",
      primarySource:"Inference from public policy", entities:["mic","fic"] },
    { id:"n_1f_interp", thread:"T1", label:"Mob crackdown created a motive", layer:"interp",
      claim:"RFK's crackdown gave the mafia a motive to kill JFK.",
      date:"1963", concreteness:"High", sourcing:"Public",
      state:"Verified", note:"Motive exists — BUT category mismatch: the mafia is not one of Dixon's complexes.",
      primarySource:"Historical record", entities:["mafia"] },
    { id:"n_2b", thread:"T1", label:"Lone gunman vs conspiracy", layer:"framing",
      claim:"Official record on whether it was a lone gunman or a conspiracy.",
      date:"1979", concreteness:"High", sourcing:"Official record",
      state:"Verified", note:"Record split. Warren (1964): lone gunman. HSCA (1979): 'probably a conspiracy' on since-discredited acoustics; NAS (1982) & FBI (1988) rebuked it.",
      primarySource:"Warren; HSCA; NAS 1982; FBI 1988", entities:["warren","hsca","assassination"] },
    { id:"n_2c", thread:"T1", label:"Orchestrated by [a structure]", layer:"framing",
      claim:"The killing was orchestrated by FIC / MIC / CIA / mafia as an institution.",
      date:"1963-11-22", concreteness:"Low", sourcing:"None / contested",
      state:"Unverifiable", note:"No official body or released file names an institutional orchestrator. 2025–26 releases show no smoking gun.",
      primarySource:"None established", entities:["assassination","fic","mic","cia","mafia"] },

    /* ============================== MIC — T2 =========================== */
    { id:"n_t2_n1", thread:"T2", label:"Primes file quarterly earnings", layer:"fact",
      claim:"Defense primes file quarterly earnings disclosing revenue sources.",
      concreteness:"High", sourcing:"Public",
      state:"Verified", note:"10-K/10-Q with segment results are public.",
      primarySource:"SEC EDGAR", entities:["primes","secfilings","mic"] },
    { id:"n_t2_n2", thread:"T2", label:"Filings disclose WHERE", layer:"fact",
      claim:"Those filings disclose geographic / contract detail showing where revenue comes from.",
      concreteness:"High", sourcing:"Public",
      state:"Partially Verified", note:"Real but coarse: backlog by customer type (US Gov, FMS, foreign govt) and net sales by broad region — not war-zone-granular.",
      primarySource:"SEC filings", entities:["primes","secfilings"] },
    { id:"n_t2_n3", thread:"T2", label:"Contracts move before the narrative", layer:"interp",
      claim:"Contracts/revenue move before the political narrative (a predictive lead).",
      concreteness:"Medium", sourcing:"Implied",
      state:"Partially Verified", note:"Leans Weak. Mostly reactive/concurrent — 'more reactive than truly predictive.' Weak long-horizon anticipation; procurement lead times.",
      primarySource:"Market/contract studies (mixed)", entities:["primes","mic"] },
    { id:"n_t2_n4", thread:"T2", label:"\"Because they prepare\"", layer:"interp",
      claim:"The MIC prepares for / anticipates specific wars (foreknowledge).",
      concreteness:"Low", sourcing:"None",
      state:"Unverifiable", note:"Benign reading (lead times) true; conspiratorial reading (engineers specific wars) unfalsifiable as stated.",
      primarySource:"None", entities:["mic"] },

    /* ============================== MIC — T3 =========================== */
    { id:"n_t3_n1", thread:"T3", label:"The 5 firms are major contractors", layer:"fact",
      claim:"Lockheed, General Dynamics, Raytheon, Boeing, BAE are major defense contractors.",
      concreteness:"High", sourcing:"Public",
      state:"Verified", note:"Roster accurate. Lockheed #1 ($64.6B 2024); RTX; GD ($93.6B backlog); Boeing; BAE (UK's largest).",
      primarySource:"Company filings / rankings", entities:["primes","lockheed","rtx","gd","boeing","bae","mic"] },
    { id:"n_t3_n1b", thread:"T3", label:"Public firms w/ fiduciary duty", layer:"fact",
      claim:"They are public companies with fiduciary duty and quarterly earnings.",
      concreteness:"High", sourcing:"Public",
      state:"Verified", note:"All publicly traded (LMT/RTX/GD/BA on NYSE; BAE on LSE).",
      primarySource:"Exchange listings", entities:["primes","secfilings"] },
    { id:"n_t3_n2_fact", thread:"T3", label:"Conflict raises revenue/backlog/profit", layer:"fact",
      claim:"Active conflict raises these firms' revenue, backlog and profit.",
      concreteness:"High", sourcing:"Public",
      state:"Verified", note:"Top-100 defense revenue $632B in 2023 (+4% real); backlogs swelled (Lockheed ~$160B, RTX ~$199B).",
      primarySource:"SIPRI / Defense News Top 100", entities:["primes","mic"] },
    { id:"n_t3_n2_interp", thread:"T3", label:"War MORE profitable than peacetime defense", layer:"interp",
      claim:"War is more profitable than peacetime defense work.",
      concreteness:"Medium", sourcing:"Implied",
      state:"Partially Verified", note:"Conflict lifts volume — true. But margins are cost-plus capped; 'war vs defense contracts' is a false binary (wartime revenue IS defense contracting, just more).",
      primarySource:"Margin analysis", entities:["mic","primes"] },

    /* ============================== FIC-1 ============================== */
    { id:"n_fic1_n1", thread:"FIC1", label:"Banks create money when they lend", layer:"fact",
      claim:"A loan simultaneously creates a matching deposit — new money as a digital entry.",
      concreteness:"High", sourcing:"Named (BoE 2014)",
      state:"Verified", note:"Bank of England, 'Money creation in the modern economy' (2014). Standard central-bank description — the conspiracy-coded claim is actually correct.",
      primarySource:"Bank of England (2014)", entities:["boe","fic"] },
    { id:"n_fic1_caveat", thread:"FIC1", label:"…but banks don't create ALL money", layer:"interp",
      claim:"Central bank issues base money/reserves; lending constrained by capital, regulation, demand.",
      concreteness:"High", sourcing:"Named",
      state:"Partially Verified", note:"Minor caveat — doesn't dent the claim.",
      primarySource:"Bank of England (2014)", entities:["fed","fic"] },

    /* ============================== FIC-2 (graduated Ponzi) ============ */
    { id:"n_fic2_n1", thread:"FIC2", label:"Money is debt; system has a growth bias", layer:"fact",
      claim:"Broad money is created as debt and destroyed on repayment; credit-expansion bias.",
      concreteness:"High", sourcing:"Implied",
      state:"Partially Verified", note:"Real kernel (cf. BIS/Minsky on debt cycles).",
      primarySource:"BIS / Minsky", entities:["fic","fed"] },
    { id:"n_fic2_n2", thread:"FIC2", label:"\"Not enough money to pay the interest\"", layer:"interp",
      claim:"There is not enough money in existence to pay the interest.",
      concreteness:"High", sourcing:"None",
      state:"Source Says Otherwise", note:"Accounting fallacy: interest is paid from circulating income FLOWS, not a fixed money STOCK; new lending replenishes. Interest is a flow, not a pre-existing stock.",
      primarySource:"Monetary accounting", entities:["fic","fed"] },
    { id:"n_fic2_n3", thread:"FIC2", label:"\"Ponzi scheme\" framing", layer:"interp",
      claim:"Central banking is a Ponzi scheme.",
      concreteness:"High", sourcing:"None",
      state:"Falsified", note:"A Ponzi has no productive assets and pays old investors from new principal; credit-money is backed by real output/assets. Rhetorical analogy, not a structural identity.",
      primarySource:"Definition match", entities:["fic","fed"] },

    /* ============================== FIC-3 ============================== */
    { id:"n_fic3_n1", thread:"FIC3", label:"Three central banks across US history", layer:"fact",
      claim:"First Bank (1791–1811), Second Bank (1816–1836), Federal Reserve (1913–).",
      concreteness:"High", sourcing:"Named",
      state:"Verified", note:"The Fed is conventionally described as the third. (First/Second were quasi-public — 'central bank' applied loosely — but 'three' is the standard count.)",
      primarySource:"Minneapolis Fed / Fed History", entities:["fed"] },

    /* ============================== FIC-4 ============================== */
    { id:"n_fic4_n1", thread:"FIC4", label:"Dutch financial pioneering", layer:"fact",
      claim:"Bank of Amsterdam (1609); VOC exchange (1602).",
      concreteness:"High", sourcing:"Named",
      state:"Verified", note:"Influential — but the Wisselbank was a municipal exchange bank, not a true central bank.",
      primarySource:"Economic history", entities:["fic"] },
    { id:"n_fic4_n2", thread:"FIC4", label:"Bank of England (1694) as template", layer:"fact",
      claim:"BoE (1694) is the modern central-bank template, copied across the Empire.",
      date:"1694", concreteness:"High", sourcing:"Named",
      state:"Verified", note:"The template that propagated.",
      primarySource:"Economic history", entities:["boe"] },
    { id:"n_fic4_n3", thread:"FIC4", label:"US three + 20th-c. proliferation (BIS/IMF)", layer:"fact",
      claim:"US → three successive institutions; then BIS (1930) / IMF (1944).",
      concreteness:"High", sourcing:"Named",
      state:"Verified", note:"The proliferation is real.",
      primarySource:"Economic history", entities:["fed","fic"] },
    { id:"n_fic4_n4", thread:"FIC4", label:"…a single 'engineered' succession", layer:"interp",
      claim:"It was one deliberate engineered succession.",
      concreteness:"Low", sourcing:"None",
      state:"Partially Verified", note:"Overstated — evolutionary diffusion, not a designed continuous project (omits e.g. Sweden's Riksbank 1668).",
      primarySource:"Historiography", entities:["fic"] },

    /* ============================== FIC-5 (graduated BlackRock) ======== */
    { id:"n_fic5_n1", thread:"FIC5", label:"Aladdin \"controls $25T\"", layer:"interp",
      claim:"Aladdin controls ~$25 trillion in capital allocation.",
      concreteness:"High", sourcing:"Implied",
      state:"Source Says Otherwise", note:"~$21–25T is MONITORED/risk-managed for 200+ external clients — not controlled/allocated. BlackRock's own AUM ≈ $11.6T (2024) → ~$14T (2025). 'Controls' is the inflation.",
      primarySource:"BlackRock disclosures", entities:["blackrock","aladdin"] },
    { id:"n_fic5_n2", thread:"FIC5", label:"\"Every central bank / SWF uses Aladdin\"", layer:"interp",
      claim:"Every pension fund, insurer, SWF, central bank and treasury uses Aladdin.",
      concreteness:"High", sourcing:"Implied",
      state:"Partially Verified", note:"Heavy hyperbole. Dominant among large managers/insurers; some official institutions engaged it (ECB/Fed crisis programs; Bank of Israel). 'Every… around the world' is categorically false.",
      primarySource:"Public reporting", entities:["blackrock","aladdin","fed"] },
    { id:"n_fic5_n3", thread:"FIC5", label:"\"Larry Fink invented the MBS\"", layer:"interp",
      claim:"Larry Fink / BlackRock invented the mortgage-backed security.",
      concreteness:"High", sourcing:"Named",
      state:"Falsified", note:"MBS predates Fink (Ginnie Mae pass-through, 1970). Fink pioneered the CMO at First Boston (~1983) — before BlackRock (1988). Kernel (CMO pioneer) is Misattributed, not 'inventor of MBS.'",
      primarySource:"Financial history", entities:["blackrock","fink"] },
    { id:"n_fic5_n4", thread:"FIC5", label:"Blythe Masters invented the CDS", layer:"fact",
      claim:"Blythe Masters invented the credit default swap.",
      concreteness:"High", sourcing:"Named",
      state:"Verified", note:"Led the JPMorgan team, mid-1990s; landmark 1994 Exxon/EBRD deal.",
      primarySource:"Financial history", entities:["bmasters"] },
    { id:"n_fic5_n5", thread:"FIC5", label:"Aramco CEO got a BlackRock board seat", layer:"fact",
      claim:"The Aramco CEO joined BlackRock's board.",
      date:"2023-07", concreteness:"High", sourcing:"Named",
      state:"Verified", note:"Amin Nasser, independent director, effective July 2023.",
      primarySource:"BlackRock proxy / press", entities:["blackrock","aramco"] },

    /* ============================== FIC-6 (hierarchy) ================== */
    { id:"n_fic6_n1", thread:"FIC6", label:"MIC firms are public & need capital", layer:"fact",
      claim:"MIC firms are public and depend on capital markets.",
      concreteness:"High", sourcing:"Public",
      state:"Verified", note:"True at the base — cross-ref MIC roster (T3).",
      primarySource:"SEC filings", entities:["mic","primes","secfilings","fic"] },
    { id:"n_fic6_n2", thread:"FIC6", label:"TIC firms subordinate b/c need capital", layer:"interp",
      claim:"TIC firms are subordinate to finance because they need capital.",
      concreteness:"High", sourcing:"Implied",
      state:"Source Says Otherwise", note:"Cash-rich giants (Apple/MSFT/Alphabet/Meta) self-fund. The 2025–26 AI-debt binge is a thin recent kernel — elective leverage from strength, not dependence. The pyramid leaks at the top.",
      primarySource:"Company cash positions", entities:["tic","fic","mag7","aicapex"] },

    /* ============================== FIC-7 ============================== */
    { id:"n_fic7_n1", thread:"FIC7", label:"Governments financed by / constrained by bonds", layer:"fact",
      claim:"Governments finance via bond markets and are constrained by them.",
      concreteness:"High", sourcing:"Public",
      state:"Verified", note:"Factual; bond-market discipline on fiscal policy is real.",
      primarySource:"Public finance", entities:["govbond","fic"] },
    { id:"n_fic7_n2", thread:"FIC7", label:"\"Piggy bank / politicians are actors\"", layer:"framing",
      claim:"Government is just a piggy bank for bondholders; politicians are WWE actors.",
      concreteness:"Low", sourcing:"None",
      state:"Unverifiable", note:"Loaded framing, not a checkable proposition. Real kernel (bond discipline) exists; park the rhetoric.",
      primarySource:"—", entities:["govbond","fic"] },

    /* ============================== FIC-8 ============================== */
    { id:"n_fic8_n1", thread:"FIC8", label:"Lobbying as influence", layer:"fact",
      claim:"The FIC exerts influence through lobbying.",
      concreteness:"High", sourcing:"Public",
      state:"Verified", note:"Documented, legal, pervasive.",
      primarySource:"Lobbying disclosures", entities:["fic","govbond"] },
    { id:"n_fic8_n2", thread:"FIC8", label:"Capital-market access as leverage", layer:"fact",
      claim:"Access to capital markets is a control lever.",
      concreteness:"High", sourcing:"Public",
      state:"Verified", note:"Real lever.",
      primarySource:"—", entities:["fic","secfilings"] },
    { id:"n_fic8_n3", thread:"FIC8", label:"\"Deep-state blackmail operations\"", layer:"interp",
      claim:"Control via deep-state black operations for blackmail.",
      concreteness:"Low", sourcing:"None",
      state:"Unverifiable", note:"No specific, checkable claim attached; unfalsifiable as stated. Tag and walk away.",
      primarySource:"—", entities:["fic"] },

    /* ============================== TIC-1 ============================== */
    { id:"n_tic1_n1", thread:"TIC1", label:"Mag 7 = record-high S&P share", layer:"fact",
      claim:"The Magnificent Seven are an extreme, record-high share of the S&P 500.",
      concreteness:"High", sourcing:"Public",
      state:"Verified", note:"Concentration story is real (~12% a decade ago).",
      primarySource:"Index data", entities:["mag7","tic"] },
    { id:"n_tic1_n2", thread:"TIC1", label:"\"Almost 50% of the S&P\"", layer:"interp",
      claim:"The Mag 7 share is almost 50%.",
      concreteness:"High", sourcing:"None",
      state:"Falsified", note:"Actual ≈ 34–35% (peak ~34.5% Aug 2025). Overstated by ~15 points — the recurring 'Mag-7 ≈ 50%' inflation tic.",
      primarySource:"S&P index weights", entities:["mag7"] },

    /* ============================== TIC-2 ============================== */
    { id:"n_tic2_n1", thread:"TIC2", label:"Algorithms shape what users see", layer:"fact",
      claim:"Recommendation algorithms shape attention, amplify content, build echo chambers.",
      concreteness:"High", sourcing:"Named",
      state:"Verified", note:"Peer-reviewed work; CRS brief.",
      primarySource:"Academic / CRS", entities:["algos","tic"] },
    { id:"n_tic2_n2", thread:"TIC2", label:"Platforms used for influence ops", layer:"fact",
      claim:"Platforms are used for coordinated influence operations.",
      concreteness:"High", sourcing:"Named",
      state:"Verified", note:"Meta adversarial-threat reports: takedowns of Russia/China/Iran state-linked networks ('Doppelganger').",
      primarySource:"Meta threat reports", entities:["algos"] },
    { id:"n_tic2_n3", thread:"TIC2", label:"\"The complex engineers perception\"", layer:"interp",
      claim:"A unified top-down technological complex directs perception.",
      concreteness:"Low", sourcing:"None",
      state:"Unverifiable", note:"Documented operators are mostly hostile STATE actors + the platforms policing them — not one coordinated complex.",
      primarySource:"—", entities:["tic","algos"] },

    /* ============================== TIC-3 (subordination) ============== */
    { id:"n_tic3_n1", thread:"TIC3", label:"Big tech depends on capital markets", layer:"interp",
      claim:"Apple/MSFT/Alphabet/Meta depend on external capital markets.",
      concreteness:"High", sourcing:"Implied",
      state:"Source Says Otherwise", note:"They are among the most cash-generative firms on earth (Alphabet >$100B cash; others >$50B) and self-fund. The dependency framing inverts the power balance.",
      primarySource:"Company balance sheets", entities:["mag7","fic","tic"] },
    { id:"n_tic3_n2", thread:"TIC3", label:"Recent AI-capex debt issuance", layer:"fact",
      claim:"Hyperscalers issued large AI-capex debt in 2025–26.",
      concreteness:"High", sourcing:"Named",
      state:"Verified", note:"Oracle $18B Sep-25 + $25B Feb-26; Meta $30B Oct-25; Amazon $15B Nov-25; Alphabet $20B Feb-26 (~$108B hyperscaler debt 2025). A real, timely kernel — finance has more leverage than a year ago.",
      primarySource:"Bond-issuance reporting", entities:["aicapex","mag7","fic"] },

    /* ============================== TIC-4 ============================== */
    { id:"n_tic4_n1", thread:"TIC4", label:"Named firms = the compute/algorithm layer", layer:"fact",
      claim:"The named firms exist and constitute the data-center / algorithm / compute layer.",
      concreteness:"High", sourcing:"Public",
      state:"Verified", note:"Trivially true. The disputes are magnitude (TIC-1), agency (TIC-2), hierarchy (TIC-3) — not membership.",
      primarySource:"—", entities:["mag7","tic","algos"] },

    /* ==================== GRIFFIN — GA (Fed = private cartel) ========== */
    { id:"n_ga_n1", thread:"GA", label:"Secret Jekyll Island meeting (1910)", layer:"fact",
      claim:"A secret meeting occurred on Jekyll Island in Nov 1910.",
      date:"1910-11", concreteness:"High", sourcing:"Implied",
      state:"Verified", note:"No longer disputed even by the Fed. Participants kept it secret until the 1930s.",
      primarySource:"Federal Reserve History; Richmond Fed", entities:["jekyll","fed","griffin"] },
    { id:"n_ga_n2", thread:"GA", label:"Attendees were the largest banks", layer:"fact",
      claim:"Attendees represented the largest US banks.",
      date:"1910-11", concreteness:"High", sourcing:"Implied",
      state:"Verified", note:"Aldrich, A. Piatt Andrew, Davison (J.P. Morgan), Vanderlip (National City/Rockefeller), Warburg (Kuhn Loeb), Shelton. Warburg's memoir confirms it.",
      primarySource:"Federal Reserve History; Warburg memoir", entities:["jekyll","fed"] },
    { id:"n_ga_n3", thread:"GA", label:"Draft → Federal Reserve Act (1913)", layer:"fact",
      claim:"The Jekyll Island draft → Aldrich Plan → Federal Reserve Act, signed Dec 23 1913.",
      date:"1913-12-23", concreteness:"High", sourcing:"Implied",
      state:"Verified", note:"Clean historical chain.",
      primarySource:"History of the Federal Reserve System", entities:["jekyll","fed"] },
    { id:"n_ga_n4", thread:"GA", label:"\"Not a govt agency — it's private\"", layer:"interp",
      claim:"The Fed is not an agency of the federal government; it is a private organization.",
      concreteness:"High", sourcing:"Asserted",
      state:"Source Says Otherwise", note:"Half-right stated as wholly right. The Fed is a hybrid: Board of Governors is a federal agency; regional banks are quasi-private (stock can't be sold/voted, 6% capped dividend). Lewis v. US (1982) called them 'privately owned' BUT also 'federal instrumentalities.' Decisive counter: the Fed remits ~all net earnings to Treasury (~$97.7B 2015) — a private cartel keeps its profit.",
      primarySource:"Federal Reserve Act §7; Lewis v. United States (9th Cir. 1982)", entities:["fed","treasury","fic","griffin"] },
    { id:"n_ga_n5", thread:"GA", label:"The Fed is a cartel", layer:"interp",
      claim:"The Fed is a cartel — competitors agreeing not to compete, controlling the market against the consumer.",
      concreteness:"Low", sourcing:"Asserted",
      state:"Partially Verified", note:"Real kernel: a government-enforced arrangement that suppresses monetary competition — genuinely cartel-like. But the defining motive (members privately splitting monopoly profit) is undercut by profits→Treasury and a public dual-mandate board. Part cartel, part public regulator; 'purely a cartel' drops the half that doesn't fit.",
      primarySource:"Structural analysis", entities:["fed","fic"] },

    /* ==================== GRIFFIN — GB (encourages war) =============== */
    { id:"n_gb_n1", thread:"GB", label:"War on terror ~$2.5T / 20 yrs", layer:"fact",
      claim:"The war on terror cost ~$2.5T over 20 years.",
      concreteness:"High", sourcing:"Named-ish",
      state:"Partially Verified", note:"Understated. Brown 'Costs of War' puts post-9/11 cost at ~$8T (incl. veterans' care + interest). $2.5T is a defensible floor, not the comprehensive number.",
      primarySource:"Brown University Costs of War", entities:["waronterror","mic"] },
    { id:"n_gb_n2", thread:"GB", label:"~$2.8T 'printed' same period", layer:"fact",
      claim:"About $2.8T was printed over the same period.",
      concreteness:"High", sourcing:"None (vague 'I think')",
      state:"Source Not Found", note:"Conflates deficit borrowing, Fed balance-sheet expansion, QE. A loose gesture, not a sourced quantity. Flagged, not chased — not load-bearing.",
      primarySource:"—", entities:["fed","waronterror"] },
    { id:"n_gb_n3", thread:"GB", label:"~$80k per US household", layer:"fact",
      claim:"That works out to ~$80,000 per US household.",
      concreteness:"High", sourcing:"Arithmetic",
      state:"Partially Verified", note:"Internally inconsistent: $2.5T ÷ 128M households ≈ $19.5k, not $80k. $80k implies ~$10T total — i.e. the larger Costs-of-War figure he didn't cite. His small number undercuts his own per-household figure.",
      primarySource:"Arithmetic check", entities:["waronterror"] },
    { id:"n_gb_n4", thread:"GB", label:"Fiscal illusion lowers resistance to war", layer:"interp",
      claim:"Hidden (inflation/debt) financing meets less voter resistance than visible taxation.",
      concreteness:"Medium", sourcing:"Named",
      state:"Verified", note:"'Fiscal illusion' is mainstream public-finance / war-finance theory (Buchanan; Rockoff). Solid as a behavioral proposition.",
      primarySource:"Buchanan; Rockoff on war finance", entities:["fed","fic","mic"] },
    { id:"n_gb_n5", thread:"GB", label:"…therefore the Fed encourages war", layer:"interp",
      claim:"Because printing hides the cost, we get more war — because of the Fed.",
      concreteness:"Low", sourcing:"Asserted",
      state:"Partially Verified", note:"Overstated. Governments waged ruinous wars on debasement for centuries before the Fed. It makes deficit-financing easier — lowers resistance — but 'encourages war' turns an enabler into a cause. Wars are driven by politics; monetary plumbing lowers the felt price.",
      primarySource:"Historical counterexamples", entities:["fed","mic","fic"] },

    /* ==================== GRIFFIN — GC (hidden tax / gold) ============ */
    { id:"n_gc_n1", thread:"GC", label:"1913 wage = 30.6 oz gold", layer:"fact",
      claim:"1913: avg wage $633; gold $20.67/oz → 30.6 oz.",
      date:"1913", concreteness:"High", sourcing:"Named",
      state:"Verified", note:"Arithmetic self-consistent (633/20.67=30.6). The $633 all-industry average is plausible (production-worker series run lower).",
      primarySource:"Griffin, book p.144", entities:["gold","fed"] },
    { id:"n_gc_n2", thread:"GC", label:"1990 wage = 52.9 oz; +73% vs +3,233%", layer:"fact",
      claim:"1990: avg wage $20,468; gold $386.90 → 52.9 oz; nominal +3,233%, gold-measured +73%.",
      date:"1990", concreteness:"High", sourcing:"Named",
      state:"Verified", note:"Math computes (20,468/386.90=52.9; 52.9/30.6=1.73; 20,468/633=32.3×).",
      primarySource:"Griffin, book p.144", entities:["gold","fed"] },
    { id:"n_gc_n3", thread:"GC", label:"73% is the REAL gain; nominal 'meaningless'", layer:"interp",
      claim:"The 73% gold-measured rise is the true gain; the 3,233% nominal rise was meaningless.",
      concreteness:"High", sourcing:"Asserted",
      state:"Partially Verified", note:"Hidden-tax kernel is sound. But it depends entirely on gold being an honest yardstick 1913→1990 — and gold was price-fixed then spiked to $850 (1980) before falling to $387. By CPI, real wages rose far more than 73% (~2–2.5×). The number is an artifact of the endpoint.",
      primarySource:"CPI deflator; gold volatility data", entities:["gold","fic"] },
    { id:"n_gc_n4", thread:"GC", label:"~1%/yr real gain came from technology", layer:"interp",
      claim:"The small real gain (~1%/yr) came from technology, not monetary policy.",
      concreteness:"Low", sourcing:"Asserted",
      state:"Partially Verified", note:"Directionally reasonable but rides on the same gold-yardstick artifact as N3.",
      primarySource:"—", entities:["gold"] },

    /* ==================== GRIFFIN — parking lot ====================== */
    { id:"n_gp_jackson", thread:"GP", label:"Jackson killed the Second Bank", layer:"parked",
      claim:"Andrew Jackson 'slayed' the central bank.",
      concreteness:"High", sourcing:"Public",
      state:"Verified", note:"Second Bank of the US: veto 1832, charter expired 1836. (Details he fumbled — 25-yr span, 'Civil War' — muddled, but the gist is right.)",
      primarySource:"Historical record", entities:["fed"] },
    { id:"n_gp_marx", thread:"GP", label:"Central banking = Marx's plank #5", layer:"parked",
      claim:"A central bank is measure #5 in Marx's 1848 Manifesto.",
      concreteness:"High", sourcing:"Named",
      state:"Verified", note:"With caveat: plank 5 demands a STATE-owned monopoly national bank — not identical to a privately-owned Fed. The plank exists; the 'Fed = Marxism' gloss is looser than the citation.",
      primarySource:"Communist Manifesto Ch.2", entities:["fic","fed"] },
    { id:"n_gp_thaler", thread:"GP", label:"'Dollar = a man named Thaler / gold nuggets'", layer:"parked",
      claim:"The dollar is named after a man called Thaler who made little round gold nuggets.",
      concreteness:"High", sourcing:"Named",
      state:"Falsified", note:"Thaler derives from the Joachimsthaler — a SILVER coin from Joachimsthal, Bohemia ('thal' = valley). Named after a PLACE, not a man; silver, not gold. The thaler→daler→dollar path is right; the origin story is invented.",
      primarySource:"Etymology (OED / Wikipedia)", entities:["gold"] },
    { id:"n_gp_amrev", thread:"GP", label:"American Revolution = escape from Bank of England", layer:"parked",
      claim:"The American Revolution was largely an escape from the Bank of England.",
      concreteness:"Medium", sourcing:"Asserted",
      state:"Partially Verified", note:"Currency control (Currency Act 1764) was A factor; 'largely' overstates vs taxation/representation/sovereignty.",
      primarySource:"—", entities:["boe"] },

    /* ==================== WEBB — WA (meta-cartel) ===================== */
    { id:"n_wa_n1", thread:"WA", label:"Operation Underworld (mob + ONI, WWII)", layer:"fact",
      claim:"A US intelligence / organized-crime alliance existed in WWII — Operation Underworld.",
      date:"1942", concreteness:"High", sourcing:"Named",
      state:"Verified", note:"US Office of Naval Intelligence worked with Luciano/Lansky to secure the NY waterfront and aid the Sicily invasion. Textbook history.",
      primarySource:"Herlands Report; History.com", entities:["opunderworld","mafia","cia"] },
    { id:"n_wa_n2", thread:"WA", label:"Denied for decades, then admitted", layer:"fact",
      claim:"The intelligence community denied the alliance for decades, then admitted it.",
      date:"1977", concreteness:"High", sourcing:"Implied",
      state:"Verified", note:"Herlands Report (1954, ~2,600pp) suppressed at Navy's request; surfaced by Rodney Campbell in 1977.",
      primarySource:"USNI Naval History", entities:["opunderworld","cia"] },
    { id:"n_wa_n3", thread:"WA", label:"Post-war intel–crime episodes", layer:"fact",
      claim:"Post-war, intelligence agencies were involved in drug/arms trafficking and crime.",
      concreteness:"High", sourcing:"Implied",
      state:"Verified", note:"CIA–Mafia Castro plots (Church Committee), Contra-cocaine (Kerry Committee), MKUltra. Intel–crime overlap is on the record — as discrete episodes.",
      primarySource:"Church Committee; Kerry Committee", entities:["cia","mafia","cia_mafia"] },
    { id:"n_wa_n4", thread:"WA", label:"…'provably continued' as one structure", layer:"interp",
      claim:"The wartime alliance provably continued as a single continuous structure that absorbed the mob's rackets.",
      concreteness:"Medium", sourcing:"Asserted",
      state:"Partially Verified", note:"Overreach. What's proven is episodic, deniable collaboration across decades — not a single unbroken organization operating the rackets wholesale. That's a synthesis, not a documented entity.",
      primarySource:"—", entities:["cia","mafia","cia_mafia"] },
    { id:"n_wa_n5", thread:"WA", label:"…therefore a meta-cartel runs the world", layer:"framing",
      claim:"Therefore the world is basically run by a single meta-cartel.",
      concreteness:"Low", sourcing:"None",
      state:"Unverifiable", note:"Approaches the unfalsifiable: participation inferred from association; departures explained as being 'popped off.' Tag as an interpretive frame, not a fact.",
      primarySource:"—", entities:["cia","mafia","epstein"] },

    /* ==================== WEBB — WB (protected asset) ================ */
    { id:"n_wb_n1", thread:"WB", label:"2008 deal was extraordinarily lenient", layer:"fact",
      claim:"Epstein's 2008 deal was ~18 months with work release.",
      concreteness:"High", sourcing:"Public",
      state:"Verified", note:"~18-month sentence, private jail wing, work release. Well documented.",
      primarySource:"Court record", entities:["epstein"] },
    { id:"n_wb_n2", thread:"WB", label:"NPA immunized co-conspirators", layer:"fact",
      claim:"The non-prosecution agreement granted immunity to named + 'potential' co-conspirators.",
      concreteness:"High", sourcing:"Named",
      state:"Verified", note:"Four named co-conspirators + 'any potential co-conspirators.' DOJ OPR confirms the clause was inserted with startlingly little deliberation.",
      primarySource:"DOJ OPR report; CVRA filings", entities:["epstein","maxwell"] },
    { id:"n_wb_n3", thread:"WB", label:"Judge ruled prosecutors broke the law", layer:"fact",
      claim:"A federal judge ruled prosecutors violated the Crime Victims' Rights Act.",
      date:"2019-02", concreteness:"High", sourcing:"Named",
      state:"Verified", note:"Judge Kenneth Marra (Feb 2019): prosecutors violated the CVRA by concealing the deal from victims. Court of record.",
      primarySource:"Marra ruling (S.D. Fla.)", entities:["epstein"] },
    { id:"n_wb_n4", thread:"WB", label:"Acosta: Epstein 'belonged to intelligence'", layer:"fact",
      claim:"Acosta said Epstein 'belonged to intelligence' / was 'above his pay grade.'",
      concreteness:"High", sourcing:"Single anonymous",
      state:"Source Says Otherwise", note:"Traces to ONE anonymous source in a 2019 Vicky Ward piece; no documents. Acosta told the House Oversight Committee he had 'no knowledge' of whether Epstein was intelligence. The most-cited 'smoking gun' is hearsay the named man denied.",
      primarySource:"Vicky Ward/Daily Beast (anon); Acosta testimony", entities:["epstein","cia"] },
    { id:"n_wb_n5", thread:"WB", label:"…therefore a protected intelligence asset", layer:"interp",
      claim:"Therefore Epstein was a protected intelligence operative and the leniency reflects that protection.",
      concreteness:"Medium", sourcing:"Asserted",
      state:"Partially Verified", note:"The deal is genuinely anomalous — but leniency has competing explanations (prosecutorial cowardice/corruption, Acosta's misjudgment, aggressive wealthy defense) the intelligence thesis doesn't defeat. One hypothesis, not a proven cause.",
      primarySource:"—", entities:["epstein","cia"] },

    /* ==================== WEBB — WC (Mossad recruitment) ============= */
    { id:"n_wc_n1", thread:"WC", label:"Maxwell had Israeli-intel ties", layer:"fact",
      claim:"Robert Maxwell had ties to Israeli intelligence.",
      concreteness:"Medium", sourcing:"Named",
      state:"Partially Verified", note:"Widely reported (Hersh's Samson Option; Gordon Thomas); Maxwell got a state funeral in Israel. Real basis for 'ties' — though the strongest specific allegations are contested.",
      primarySource:"Hersh; Gordon Thomas", entities:["maxwell","mossad"] },
    { id:"n_wc_n2", thread:"WC", label:"Ben-Menashe: Maxwell recruited Epstein", layer:"fact",
      claim:"Ari Ben-Menashe says Maxwell personally introduced/recruited Epstein for Israeli intelligence.",
      concreteness:"High", sourcing:"Single named (low reliability)",
      state:"Unverifiable", note:"Primary witness is Ari Ben-Menashe — repeatedly assessed by governments and journalists as an unreliable fabulist. A load-bearing recruitment claim resting on him is structurally weak.",
      primarySource:"Ben-Menashe (contested)", entities:["maxwell","epstein","benmenashe","mossad"] },
    { id:"n_wc_n3", thread:"WC", label:"'Corroborated by Hersh & Gordon Thomas'", layer:"fact",
      claim:"The recruitment claim is corroborated thanks to Gordon Thomas and Seymour Hersh.",
      concreteness:"High", sourcing:"Named (compromised)",
      state:"Source Says Otherwise", note:"Shakier than advertised: part of Hersh's Maxwell reporting was built on a documented hoax (a British hoaxer conned his publisher); Gordon Thomas is a sensationalist thriller writer. The 'corroboration' is compromised, not independent.",
      primarySource:"Gale/Newsweek 'Author hoaxed over Maxwell'", entities:["maxwell","benmenashe"] },
    { id:"n_wc_n4", thread:"WC", label:"…therefore Epstein was a Mossad asset", layer:"interp",
      claim:"Therefore Epstein was a Mossad-linked asset via Maxwell.",
      concreteness:"Low", sourcing:"Inherited",
      state:"Unverifiable", note:"Inherits the weakness of N2–N3. Not 'false' — unproven on the evidence offered.",
      primarySource:"—", entities:["epstein","mossad"] },

    /* ==================== WEBB — WD (Middleton cover-up) ============= */
    { id:"n_wd_n1", thread:"WD", label:"17 White House visits (1993–95)", layer:"fact",
      claim:"Epstein visited the Clinton White House ~17 times, 1993–Jan 1995.",
      date:"1993", concreteness:"High", sourcing:"Public",
      state:"Verified", note:"Visitor logs / records; cited in reporting and congressional questioning.",
      primarySource:"WH visitor records", entities:["epstein","clinton"] },
    { id:"n_wd_n2", thread:"WD", label:"Middleton facilitated the access", layer:"fact",
      claim:"Most visits were with/cleared by Mark Middleton, who left Feb 1995.",
      concreteness:"High", sourcing:"Public",
      state:"Partially Verified", note:"Middleton documented facilitating access in 'at least three instances' + flew on Epstein's jet (May 1994). 'Most of the 17' goes beyond the firmly established count — directionally supported, exact share not confirmed.",
      primarySource:"Reporting on Middleton", entities:["epstein","clinton","middleton"] },
    { id:"n_wd_n3", thread:"WD", label:"Extent revealed 2022; death months later", layer:"fact",
      claim:"The fuller extent came out in 2022; Middleton died months later.",
      date:"2022-05", concreteness:"High", sourcing:"Public",
      state:"Verified", note:"Reported 2022; Middleton died May 7, 2022.",
      primarySource:"Reporting", entities:["middleton"] },
    { id:"n_wd_n4", thread:"WD", label:"Grotesque death; records sealed", layer:"fact",
      claim:"Death: extension-cord hanging + shotgun wound to chest; gun first absent then found ~30 ft away; records sealed.",
      date:"2022-05", concreteness:"High", sourcing:"Public",
      state:"Verified", note:"Heifer Ranch, AR: hanging by extension cord with self-inflicted shotgun wound; 12-gauge ~30 ft away; judge sealed photos/video. Ruled suicide.",
      primarySource:"Arkansas Times; Encyclopedia of Arkansas", entities:["middleton"] },
    { id:"n_wd_n5", thread:"WD", label:"…therefore a cover-up (China Gate)", layer:"framing",
      claim:"Therefore Middleton's death is a suspicious cover-up tied to Epstein / 'China Gate.'",
      concreteness:"Low", sourcing:"None",
      state:"Unverifiable", note:"Temporal-adjacency inference. Ruled suicide; critically, the sealing was requested by Middleton's OWN FAMILY to stop conspiracy theories — a mundane explanation that fits the facts at least as well. Webb herself concedes uncertainty.",
      primarySource:"—", entities:["middleton","epstein"] },

    /* ==================== WEBB — WE (BCCI) =========================== */
    { id:"n_we_n1", thread:"WE", label:"Senate BCCI report: teen-girl procurement", layer:"fact",
      claim:"The 1992 Kerry–Brown BCCI report documents the bank procuring underage/teenage girls for powerful clients.",
      date:"1992", concreteness:"High", sourcing:"Named (the report)",
      state:"Verified", note:"Documents a 'protocol department' procuring 'virgin women from the villages, ages 16–20,' paying families, supplying royalty/Gulf clients. 16 is a minor; the pattern is trafficking-like. WaPo (1992) confirms the testimony.",
      primarySource:"Kerry–Brown 'BCCI Affair' report; WaPo 1992", entities:["bcci"] },
    { id:"n_we_n2", thread:"WE", label:"…citing it as established is legitimate", layer:"interp",
      claim:"Citing the Senate report as establishing institutional trafficking is legitimate.",
      concreteness:"High", sourcing:"Named",
      state:"Verified", note:"Precision dock only: the report frames it as procurement for the bank's CLIENTS/royalty, slightly different from Webb's 'members of the bank.' Kernel is solidly there.",
      primarySource:"Kerry–Brown report", entities:["bcci"] },

    /* ==================== WEBB — parking (weld points) ============== */
    { id:"n_wp_dulles", thread:"WP", label:"CIA's early coups for oil & United Fruit", layer:"parked",
      claim:"The CIA's earliest coups (Iran 1953, Guatemala 1954) were for Anglo-Iranian Oil and United Fruit; run by the Dulles brothers.",
      date:"1953", concreteness:"High", sourcing:"Public",
      state:"Verified", note:"Standard history; United Fruit ties to the Dulles brothers well documented. (Not load-bearing to Epstein — but the same Allen Dulles JFK later fired.)",
      primarySource:"Historical record", entities:["cia"] },
    { id:"n_wp_palantir", thread:"WP", label:"Palantir = privatized 'Total Information Awareness'", layer:"parked",
      claim:"DARPA's TIA (Poindexter) was privatized as Palantir; In-Q-Tel funded it; CIA was first client.",
      concreteness:"High", sourcing:"Public",
      state:"Partially Verified", note:"Hard facts largely verified (In-Q-Tel early investor; CIA early client; Poindexter ran TIA). 'Palantir = privatized TIA by design' is the interpretive causal add-on. Welds the intel domain to TIC.",
      primarySource:"Public reporting", entities:["palantir","cia","tic"] },
    { id:"n_wp_bae", thread:"WP", label:"Prince Andrew lobbying for BAE / Al-Yamamah", layer:"parked",
      claim:"Prince Andrew as UK trade rep lobbied for BAE (Al-Yamamah); Epstein-linked framing.",
      concreteness:"Medium", sourcing:"Public",
      state:"Partially Verified", note:"Andrew's trade-envoy role + BAE/Saudi arms controversy are real; the specific Epstein-linked framing is looser. Welds IIC to the MIC roster (BAE).",
      primarySource:"Public reporting", entities:["bae","epstein"] },
    { id:"n_wp_mbs", thread:"WP", label:"MBS / Vision 2030 — Epstein 'architect'", layer:"parked",
      claim:"Epstein was an architect of MBS's Vision 2030 and managed a Saudi sovereign wealth fund.",
      concreteness:"Low", sourcing:"None",
      state:"Unverifiable", note:"Webb explicitly flags this section as 'inherently speculative.' Tag and walk away. (Touches Saudi/Aramco — welds toward FIC.)",
      primarySource:"—", entities:["epstein","aramco"] },
    { id:"n_wp_bear", thread:"WP", label:"Epstein 'popped' Bear Stearns", layer:"parked",
      claim:"Epstein was the pin that popped Bear Stearns; his bank JPMorgan absorbed it.",
      concreteness:"Medium", sourcing:"None",
      state:"Partially Verified", note:"MIXED: Bear Stearns collapsed and JPMorgan absorbed it (true); the 'Epstein popped it' causal claim is unsupported.",
      primarySource:"—", entities:["epstein","fic"] },

    /* ==================== OPEN RECONCILIATION (Contested) ============= */
    { id:"n_rx_fedcontrol", thread:"RX1", label:"Is the Fed a private cartel, or a govt-controlled hybrid?", layer:"framing",
      claim:"Two sources collide on WHO controls the core monetary institution. Dixon's frame: the FIC (private finance) sits above government. Griffin's own analysis: the Fed remits ~all profit to Treasury and answers to a public board — a government-controlled hybrid, not a purely private cartel.",
      concreteness:"High", sourcing:"Two sources in conflict",
      state:"Contested", note:"UNRESOLVED. Resolves toward 'publicly-controlled' if Treasury-remittance + public-board governance are decisive; toward 'private apex' if regulatory capture / revolving-door control is shown to dominate the formal structure. Research owed: quantify de-facto vs de-jure control. Neither source is decisively right; do not pick a winner.",
      primarySource:"needs research", entities:["fed","fic","treasury"] },

    { id:"n_rx_apex", thread:"RX1", label:"What sits at the apex — finance, or an intelligence-crime meta-cartel?", layer:"framing",
      claim:"Two sources offer competing grand theories of who really runs things. Dixon: the Financial-Industrial Complex (capital) sits above every other structure. Webb: an intelligence-crime 'meta-cartel' (born of Operation Underworld) is the deeper layer. Each frames the other's apex as a subordinate instrument.",
      concreteness:"Low", sourcing:"Two sources in conflict",
      state:"Contested", note:"UNRESOLVED — and possibly a false dichotomy (they may be the same elite from two vantage points). Both apex claims are the WEAKEST-graded parts of their own threads (Dixon's FIC-hierarchy is 'Weak'; Webb's meta-cartel is 'Unverifiable'). Research owed: is there a testable structural claim here at all, or two unfalsifiable frames? Do not pick a winner.",
      primarySource:"needs research", entities:["fic","cia_mafia","epstein"] },

    /* ============================== PARKING LOT ======================== */
    { id:"n_pl_trump", thread:"PL", label:"Trump as 'challenged the structure'", layer:"parked",
      claim:"Dixon's aside: Trump as another example.",
      concreteness:"Low", sourcing:"None", state:"Open",
      note:"Parked during the JFK dive. Not yet decomposed.", entities:["dixon","fic"] },
    { id:"n_pl_kirk", thread:"PL", label:"Charlie Kirk as an example", layer:"parked",
      claim:"Dixon's aside: Charlie Kirk as an example.",
      concreteness:"Low", sourcing:"None", state:"Open",
      note:"Parked. Not yet decomposed.", entities:["dixon"] },
    { id:"n_pl_mictic", thread:"PL", label:"MIC ↔ TIC edge — does it exist?", layer:"parked",
      claim:"Is there a real MIC↔TIC link, or does everything route through the FIC?",
      concreteness:"Low", sourcing:"None", state:"Open",
      note:"Still parked — but TIC-3 (tech as financial PEER, not subordinate) is the first real evidence bearing on it. Revisit when the parking lot opens.",
      entities:["mic","tic","fic"] }
  ],

  /* ------------------------------------------------------------------ EDGES */
  edges: [

    /* ===== MIC — T1 ===== */
    { id:"e_1a", thread:"T1", from:"n_1a_fact",  to:"n_1a_interp", type:"cites_as_evidence", grade:"Unwarranted",
      note:"EO 11110 read as anti-Fed; the document shows the opposite." },
    { id:"e_1c", thread:"T1", from:"n_1c_fire",  to:"n_1c_interp", type:"cites_as_evidence", grade:"Weak",
      note:"Firing Dulles is real; 'dismantle the CIA' overstates it." },
    { id:"e_1cq", thread:"T1", from:"n_1c_quote", to:"n_1c_interp", type:"cites_as_evidence", grade:"Unwarranted",
      note:"Unsourced quote can't carry the 'dismantle' intent." },
    { id:"e_1d", thread:"T1", from:"n_1d_fact",  to:"n_1d_interp", type:"cites_as_evidence", grade:"Weak",
      note:"NSAM 263 real; that it = a firm exit decision is historically disputed." },
    { id:"e_1e", thread:"T1", from:"n_1e_fact",  to:"n_1e_interp", type:"cites_as_evidence", grade:"Weak",
      note:"Détente real; 'threatened the structure' is speculative." },
    { id:"e_1f", thread:"T1", from:"n_1f_fact",  to:"n_1f_interp", type:"cites_as_evidence", grade:"Warranted",
      note:"Crackdown genuinely creates a mafia motive — but outside Dixon's complexes." },
    { id:"e_motive", thread:"T1", from:"n_1a_interp", to:"n_2c", type:"causal_inference", grade:"Unwarranted",
      note:"E-motive: FIC-motive nodes (1a/1b) Falsified → no motive there. Surviving motives point away from Dixon's thesis." },
    { id:"e_mechanism", thread:"T1", from:"n_2c", to:"n_2a", type:"causal_inference", grade:"NonSequitur",
      note:"E-mechanism: no node establishes orchestration; mechanism Unverifiable, so asserting it is a non sequitur." },

    /* ===== MIC — T2 ===== */
    { id:"e_t2_1", thread:"T2", from:"n_t2_n2", to:"n_t2_n3", type:"predictive", grade:"Weak",
      note:"E1: filings → 'determine the next war zone.' Legitimate kernel overstated off a coarse, mostly-reactive indicator." },
    { id:"e_t2_2", thread:"T2", from:"n_t2_n4", to:"n_t2_n3", type:"causal_inference", grade:"Unwarranted",
      note:"E2: 'because they prepare' → MIC foresees/drives the war. Leading ≠ causing ≠ foreknowledge." },

    /* ===== MIC — T3 ===== */
    { id:"e_t3_1", thread:"T3", from:"n_t3_n1b", to:"n_t3_n2_interp", type:"incentive", grade:"Warranted",
      note:"E1: public firms structurally seek growing revenue (fiduciary duty). Nearly tautological; sound." },
    { id:"e_t3_2", thread:"T3", from:"n_t3_n2_fact", to:"n_t3_n2_interp", type:"incentive", grade:"Weak",
      note:"E2: '…requires WAR specifically.' Overstated — sustained by high baseline budgets. War is upside, not baseline." },

    /* ===== FIC ===== */
    { id:"e_fic2", thread:"FIC2", from:"n_fic2_n1", to:"n_fic2_n3", type:"causal_inference", grade:"Unwarranted",
      note:"Debt-money + growth-bias (real) → 'mathematically must collapse / Ponzi.' The catastrophic inference rests on the false 'not enough money' mechanism (n_fic2_n2), so it isn't licensed." },
    { id:"e_fic2b", thread:"FIC2", from:"n_fic2_n2", to:"n_fic2_n3", type:"cites_as_evidence", grade:"Unwarranted",
      note:"The 'not enough money to pay interest' fallacy is what props up the Ponzi framing." },
    { id:"e_fic4", thread:"FIC4", from:"n_fic4_n3", to:"n_fic4_n4", type:"causal_inference", grade:"Weak",
      note:"Real lineage/diffusion → 'proof of intentional engineered design.' 'Engineered' smuggles in intent." },
    { id:"e_fic5", thread:"FIC5", from:"n_fic5_n1", to:"n_fic5_n2", type:"depends_on", grade:"Weak",
      note:"The '$25T controls' inflation feeds the 'every institution uses it' hyperbole — both confuse footprint with control." },
    { id:"e_fic6", thread:"FIC6", from:"n_fic6_n1", to:"n_fic6_n2", type:"depends_on", grade:"Weak",
      note:"'All complexes need capital → FIC sits above all.' True for MIC (base), overstated for cash-rich TIC (top). Pyramid real at the base, leaky at the top." },

    /* ===== TIC ===== */
    { id:"e_tic1", thread:"TIC1", from:"n_tic1_n1", to:"n_tic2_n3", type:"cites_as_evidence", grade:"Weak",
      note:"Real concentration → 'TIC is a coherent, coordinated power bloc.' The coordination is the interpretive add-on (lands on TIC-2's agency overreach)." },
    { id:"e_tic2", thread:"TIC2", from:"n_tic2_n1", to:"n_tic2_n3", type:"causal_inference", grade:"Unwarranted",
      note:"Capability exists → 'a coordinating complex wields it.' Mechanism real; coordinated-agency leap asserted, not shown." },
    { id:"e_tic3", thread:"TIC3", from:"n_tic3_n2", to:"n_tic3_n1", type:"causal_inference", grade:"Unwarranted",
      note:"They tap debt markets → 'subordinate to finance.' Elective leverage from strength ≠ structural subordination." },

    /* ===== CROSS-COMPLEX WELD: the same hierarchy debate, two sides ===== */
    { id:"e_cross_hier", thread:"FIC6", from:"n_tic3_n1", to:"n_fic6_n2", type:"same_entity", grade:"Unwarranted",
      note:"CROSSOVER: FIC-6 (finance sits above all) and TIC-3 (tech self-funds) are the SAME claim from opposite sides. The FIC pyramid leaks exactly where TIC-3 shows the cash-rich giants self-funding." },

    /* ===== GRIFFIN internal inference edges ===== */
    { id:"e_ga_1", thread:"GA", from:"n_ga_n3", to:"n_ga_n5", type:"causal_inference", grade:"Weak",
      note:"Secret bankers' meeting → therefore a private cartel against the public. Motive-suggestive (bankers designing their own regulator), not structure-determinative." },
    { id:"e_ga_2", thread:"GA", from:"n_ga_n4", to:"n_ga_n5", type:"cites_as_evidence", grade:"Weak",
      note:"'Not a govt agency' is stated too strongly to carry 'purely a cartel' — undercut by Treasury remittance + public board." },
    { id:"e_gb_1", thread:"GB", from:"n_gb_n4", to:"n_gb_n5", type:"causal_inference", grade:"Weak",
      note:"Fiscal illusion lowers resistance to war → 'the Fed causes more war.' Enabler overstated as cause." },
    { id:"e_gc_1", thread:"GC", from:"n_gc_n2", to:"n_gc_n3", type:"depends_on", grade:"Weak",
      note:"The whole 73% conclusion depends on gold being a valid yardstick — over the one span where gold was least stable (fixed, then a 1970s moonshot)." },

    /* ===== CROSS-SOURCE RECONCILIATION edges (Griffin ↔ existing web) ===== */
    { id:"e_rec_jekyll", from:"n_ga_n3", to:"n_fic4_n3", type:"corroborates",
      note:"CORROBORATE: an independent source confirms the US central-bank 'engineering' chain (Jekyll Island 1910 → Fed Act 1913) that Dixon's FIC-4 asserted. Confidence up." },
    { id:"e_rec_engineered", from:"n_ga_n1", to:"n_fic4_n4", type:"clarifies",
      note:"CLARIFY: Griffin supplies the concrete secret meeting Dixon's 'engineered succession' only gestured at — yet Griffin's own edge also grades the 'deliberate design' leap as overstated. Two sources independently converge on the same caution." },
    { id:"e_rec_hiddentax", from:"n_gc_n3", to:"n_fic2_n1", type:"corroborates",
      note:"CORROBORATE: second source backs the inflation-as-hidden-tax / debt-money kernel (though Griffin's specific gold proof over-reaches, same as Dixon's Ponzi over-reach)." },
    { id:"e_rec_war", from:"n_gb_n5", to:"n_t3_n2_interp", type:"parallels",
      note:"PARALLEL (non-probative): Griffin (monetary fiscal-illusion) and Dixon (contractor profit incentive) both argue structural forces tilt toward war — but via DIFFERENT mechanisms, and both of these are the OVERSTATED ends of their threads (each graded weak/overstated). A thematic echo, not mutual proof. Do not read as corroboration." },
    { id:"e_rec_jackson", from:"n_gp_jackson", to:"n_fic3_n1", type:"corroborates",
      note:"CORROBORATE: confirms the Second Bank chapter of Dixon's 'three central banks.'" },

    /* ===== CONTEST: the one genuine standoff → held in RX, not adjudicated ===== */
    { id:"e_rec_contest_g", from:"n_rx_fedcontrol", to:"n_ga_n4", type:"contests", status:"open",
      note:"Griffin's side of the standoff: the Fed remits ~all profit to Treasury and answers to a public board — a govt-controlled hybrid." },
    { id:"e_rec_contest_d", from:"n_rx_fedcontrol", to:"n_fic7_n2", type:"contests", status:"open",
      note:"Dixon's side: government is a 'piggy bank for bondholders' — finance controls the state. Both can't be wholly right; research owed." },

    /* ===== WEBB internal inference edges ===== */
    { id:"e_wa_1", thread:"WA", from:"n_wa_n3", to:"n_wa_n5", type:"causal_inference", grade:"Weak",
      note:"Episodic intel–crime scandals → 'one continuous meta-cartel runs the world.' E-history is Warranted; the weld to a permanent structure is not licensed by episodic collaboration." },
    { id:"e_wa_2", thread:"WA", from:"n_wa_n1", to:"n_wa_n4", type:"depends_on", grade:"Weak",
      note:"'Provably continued' leans on the founding fact but claims a continuity the record doesn't prove." },
    { id:"e_wb_1", thread:"WB", from:"n_wb_n4", to:"n_wb_n5", type:"cites_as_evidence", grade:"Weak",
      note:"A real, unlawfully-handled deal is used to license a specific unproven cause (intelligence protection) — resting on the contested, denied Acosta quote." },
    { id:"e_wc_1", thread:"WC", from:"n_wc_n2", to:"n_wc_n4", type:"cites_as_evidence", grade:"Unwarranted",
      note:"The inference is only as strong as its sources — here a contested fabulist (Ben-Menashe) plus partially-hoaxed/sensational authors. 'Ties' stretched into 'recruitment.'" },
    { id:"e_wd_1", thread:"WD", from:"n_wd_n4", to:"n_wd_n5", type:"temporal", grade:"Weak",
      note:"Strange suicide close in time to a news cycle → 'cover-up.' Temporal adjacency, not proof; the family-requested seal fits the facts at least as well." },
    { id:"e_we_1", thread:"WE", from:"n_we_n1", to:"n_we_n2", type:"cites_as_evidence", grade:"Warranted",
      note:"The report does say substantially what she claims; citing it as established is legitimate. Docks are precision-level only. (A rare Warranted edge.)" },

    /* ===== CROSS-SOURCE RECONCILIATION: Webb ↔ existing web ===== */
    { id:"e_rec_dulles", from:"n_wp_dulles", to:"n_1c_fire", type:"corroborates",
      note:"CORROBORATE across sources & domains: Webb's Dulles-brothers coups and Dixon's JFK 'fired Allen Dulles' node land on the SAME Allen Dulles — independently establishing him as a major covert-power figure." },
    { id:"e_rec_coverup", from:"n_wd_n5", to:"n_2c", type:"parallels",
      note:"PARALLEL (non-probative): Webb's Middleton 'death → cover-up' and Dixon's JFK 'assassination → orchestrated by a structure' share the SAME failure signature — real strange facts welded to an unproven institutional-cover-up conclusion. A recurring pattern to watch, not mutual proof." },
    { id:"e_rec_apex_w", from:"n_rx_apex", to:"n_wa_n5", type:"contests", status:"open",
      note:"Webb's apex: an intelligence-crime meta-cartel is the deepest layer." },
    { id:"e_rec_apex_d", from:"n_rx_apex", to:"n_fic6_n1", type:"contests", status:"open",
      note:"Dixon's apex: the FIC (capital) sits above all — every complex needs capital. The two grand theories collide here." }
  ]
};
